// <auto-generated />
using System;
using Giretra.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Giretra.Model.Migrations
{
    [DbContext(typeof(GiretraDbContext))]
    [Migration("20260219225429_AddBotRating")]
    partial class AddBotRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Giretra.Model.Entities.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_blocks_blocked_id");

                    b.HasIndex("BlockerId")
                        .HasDatabaseName("ix_blocks_blocker_id");

                    b.HasIndex("BlockerId", "BlockedId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_blocker_id_blocked_id");

                    b.ToTable("blocks", null, t =>
                        {
                            t.HasCheckConstraint("chk_no_self_block", "blocker_id != blocked_id");
                        });
                });

            modelBuilder.Entity("Giretra.Model.Entities.Bot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("difficulty");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_bots");

                    b.HasIndex("AgentType")
                        .IsUnique()
                        .HasDatabaseName("ix_bots_agent_type");

                    b.ToTable("bots", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AnnouncerTeam")
                        .HasColumnType("integer")
                        .HasColumnName("announcer_team");

                    b.Property<bool?>("AnnouncerWon")
                        .HasColumnType("boolean")
                        .HasColumnName("announcer_won");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<short>("DealNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("deal_number");

                    b.Property<int>("DealerPosition")
                        .HasColumnType("integer")
                        .HasColumnName("dealer_position");

                    b.Property<int?>("GameMode")
                        .HasColumnType("integer")
                        .HasColumnName("game_mode");

                    b.Property<bool>("IsInstantWin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_instant_win");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Multiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("multiplier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int?>("SweepingTeam")
                        .HasColumnType("integer")
                        .HasColumnName("sweeping_team");

                    b.Property<int?>("Team1CardPoints")
                        .HasColumnType("integer")
                        .HasColumnName("team1card_points");

                    b.Property<int?>("Team1MatchPoints")
                        .HasColumnType("integer")
                        .HasColumnName("team1match_points");

                    b.Property<int?>("Team2CardPoints")
                        .HasColumnType("integer")
                        .HasColumnName("team2card_points");

                    b.Property<int?>("Team2MatchPoints")
                        .HasColumnType("integer")
                        .HasColumnName("team2match_points");

                    b.Property<bool>("WasSweep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("was_sweep");

                    b.HasKey("Id")
                        .HasName("pk_deals");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_deals_match_id");

                    b.HasIndex("MatchId", "DealNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_deals_match_id_deal_number");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.DealAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("ActionOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("action_order");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<int?>("CardRank")
                        .HasColumnType("integer")
                        .HasColumnName("card_rank");

                    b.Property<int?>("CardSuit")
                        .HasColumnType("integer")
                        .HasColumnName("card_suit");

                    b.Property<bool?>("CutFromTop")
                        .HasColumnType("boolean")
                        .HasColumnName("cut_from_top");

                    b.Property<short?>("CutPosition")
                        .HasColumnType("smallint")
                        .HasColumnName("cut_position");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<int?>("GameMode")
                        .HasColumnType("integer")
                        .HasColumnName("game_mode");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("integer")
                        .HasColumnName("player_position");

                    b.Property<short?>("TrickNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("trick_number");

                    b.HasKey("Id")
                        .HasName("pk_deal_actions");

                    b.HasIndex("DealId", "ActionOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_deal_actions_deal_id_action_order");

                    b.ToTable("deal_actions", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.EloHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("EloAfter")
                        .HasColumnType("integer")
                        .HasColumnName("elo_after");

                    b.Property<int>("EloBefore")
                        .HasColumnType("integer")
                        .HasColumnName("elo_before");

                    b.Property<int>("EloChange")
                        .HasColumnType("integer")
                        .HasColumnName("elo_change");

                    b.Property<bool>("InvolvedBots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("involved_bots");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_elo_histories");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_elo_histories_match_id");

                    b.HasIndex("PlayerId", "MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_elo_histories_player_id_match_id");

                    b.HasIndex("PlayerId", "RecordedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_elo_history_bot_gains")
                        .HasFilter("involved_bots = TRUE AND elo_change > 0");

                    b.ToTable("elo_histories", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_friendships");

                    b.HasIndex("AddresseeId")
                        .HasDatabaseName("ix_friendships_addressee_id")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_friendships_requester_id")
                        .HasFilter("status = 'accepted'");

                    b.ToTable("friendships", null, t =>
                        {
                            t.HasCheckConstraint("chk_no_self_friend", "requester_id != addressee_id");
                        });
                });

            modelBuilder.Entity("Giretra.Model.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsRanked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_ranked");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TargetScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(150)
                        .HasColumnName("target_score");

                    b.Property<int>("Team1FinalScore")
                        .HasColumnType("integer")
                        .HasColumnName("team1final_score");

                    b.Property<int>("Team2FinalScore")
                        .HasColumnType("integer")
                        .HasColumnName("team2final_score");

                    b.Property<int>("TotalDeals")
                        .HasColumnType("integer")
                        .HasColumnName("total_deals");

                    b.Property<bool>("WasAbandoned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("was_abandoned");

                    b.Property<int?>("WinnerTeam")
                        .HasColumnType("integer")
                        .HasColumnName("winner_team");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("CompletedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_matches_completed_at");

                    b.HasIndex("IsRanked")
                        .HasDatabaseName("ix_matches_is_ranked")
                        .HasFilter("is_ranked = TRUE");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.MatchPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("EloAfter")
                        .HasColumnType("integer")
                        .HasColumnName("elo_after");

                    b.Property<int?>("EloBefore")
                        .HasColumnType("integer")
                        .HasColumnName("elo_before");

                    b.Property<int?>("EloChange")
                        .HasColumnType("integer")
                        .HasColumnName("elo_change");

                    b.Property<bool>("IsWinner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_winner");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("Team")
                        .HasColumnType("integer")
                        .HasColumnName("team");

                    b.HasKey("Id")
                        .HasName("pk_match_players");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_match_players_match_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_match_players_player_id");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_players_match_id_player_id");

                    b.HasIndex("MatchId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_match_players_match_id_position");

                    b.ToTable("match_players", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BestWinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("best_win_streak");

                    b.Property<Guid?>("BotId")
                        .HasColumnType("uuid")
                        .HasColumnName("bot_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EloIsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("elo_is_public");

                    b.Property<int>("EloRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("elo_rating");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("games_played");

                    b.Property<int>("GamesWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("games_won");

                    b.Property<string>("PlayerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("player_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("win_streak");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("BotId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_bot_id")
                        .HasFilter("bot_id IS NOT NULL");

                    b.HasIndex("EloRating")
                        .IsDescending()
                        .HasDatabaseName("ix_players_elo_rating")
                        .HasFilter("elo_is_public = TRUE");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("players", null, t =>
                        {
                            t.HasCheckConstraint("chk_player_type_ref", "(player_type = 'human' AND user_id IS NOT NULL AND bot_id IS NULL) OR (player_type = 'bot' AND bot_id IS NOT NULL AND user_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Giretra.Model.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("BotCount")
                        .HasColumnType("smallint")
                        .HasColumnName("bot_count");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_player_id");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short>("PlayerCount")
                        .HasColumnType("smallint")
                        .HasColumnName("player_count");

                    b.Property<int>("TurnTimerSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("turn_timer_seconds");

                    b.Property<short>("WatcherCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("watcher_count");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("CreatorPlayerId")
                        .HasDatabaseName("ix_rooms_creator_player_id");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_match_id")
                        .HasFilter("match_id IS NOT NULL");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("custom_display_name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("normal")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_keycloak_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Giretra.Model.Entities.Block", b =>
                {
                    b.HasOne("Giretra.Model.Entities.User", "Blocked")
                        .WithMany("BlocksReceived")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_users_blocked_id");

                    b.HasOne("Giretra.Model.Entities.User", "Blocker")
                        .WithMany("BlocksInitiated")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_users_blocker_id");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Deal", b =>
                {
                    b.HasOne("Giretra.Model.Entities.Match", "Match")
                        .WithMany("Deals")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deals_matches_match_id");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Giretra.Model.Entities.DealAction", b =>
                {
                    b.HasOne("Giretra.Model.Entities.Deal", "Deal")
                        .WithMany("DealActions")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deal_actions_deals_deal_id");

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("Giretra.Model.Entities.EloHistory", b =>
                {
                    b.HasOne("Giretra.Model.Entities.Match", "Match")
                        .WithMany("EloHistories")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_elo_histories_matches_match_id");

                    b.HasOne("Giretra.Model.Entities.Player", "Player")
                        .WithMany("EloHistories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_elo_histories_players_player_id");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Friendship", b =>
                {
                    b.HasOne("Giretra.Model.Entities.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_addressee_id");

                    b.HasOne("Giretra.Model.Entities.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_requester_id");

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Giretra.Model.Entities.MatchPlayer", b =>
                {
                    b.HasOne("Giretra.Model.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_players_matches_match_id");

                    b.HasOne("Giretra.Model.Entities.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_players_players_player_id");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Player", b =>
                {
                    b.HasOne("Giretra.Model.Entities.Bot", "Bot")
                        .WithOne("Player")
                        .HasForeignKey("Giretra.Model.Entities.Player", "BotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_players_bots_bot_id");

                    b.HasOne("Giretra.Model.Entities.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("Giretra.Model.Entities.Player", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_players_users_user_id");

                    b.Navigation("Bot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Room", b =>
                {
                    b.HasOne("Giretra.Model.Entities.Player", "CreatorPlayer")
                        .WithMany("CreatedRooms")
                        .HasForeignKey("CreatorPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_players_creator_player_id");

                    b.HasOne("Giretra.Model.Entities.Match", "Match")
                        .WithOne("Room")
                        .HasForeignKey("Giretra.Model.Entities.Room", "MatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rooms_matches_match_id");

                    b.Navigation("CreatorPlayer");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Bot", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Deal", b =>
                {
                    b.Navigation("DealActions");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Match", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("EloHistories");

                    b.Navigation("MatchPlayers");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Giretra.Model.Entities.Player", b =>
                {
                    b.Navigation("CreatedRooms");

                    b.Navigation("EloHistories");

                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("Giretra.Model.Entities.User", b =>
                {
                    b.Navigation("BlocksInitiated");

                    b.Navigation("BlocksReceived");

                    b.Navigation("Player");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
